import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useUser } from "@clerk/nextjs";

const Login: NextPage = () => {
	const router = useRouter();
	const { user } = useUser();
	if (user?.id) router.push("/user/me/chain");

	return (
		<>
			<Head>
				<title>ChainLinkk - Login</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="flex h-screen items-center justify-center bg-slate-600">
				<div className="flex h-20 w-72 flex-col justify-center gap-2 rounded border-2 border-black align-middle text-white">
					<p className="text-center">Please log in</p>
					<button
						className="text-purple-500"
						onClick={() => console.log("signing in")}
					>
						Sign in with Twitch
					</button>
				</div>
			</div>
		</>
	);
};
export default Login;
